-- EasySell Database Backup
-- Generated by Antigravity AI
-- Date: 5/6/2026, 2:41:55 PM

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


-- Table structure for `admin_users`
DROP TABLE IF EXISTS `admin_users`;
CREATE TABLE `admin_users` (
  `id` int NOT NULL,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `role` enum('admin','employee') NOT NULL DEFAULT 'employee',
  `is_blocked` tinyint(1) NOT NULL DEFAULT '0',
  `auth_version` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Dumping data for `admin_users`
INSERT INTO `admin_users` (`id`, `username`, `password`, `role`, `is_blocked`, `auth_version`) VALUES (1, 'admin', '$2b$10$rEXuyFXPUj.hU94I8VhoRO2CzCKAj4Jl2SwKzyiW10membYvKOTFy', 'admin', 0, 1);
INSERT INTO `admin_users` (`id`, `username`, `password`, `role`, `is_blocked`, `auth_version`) VALUES (2, 'addd', '$2b$10$CVxYrASBuUx46nHkAb9PbOmeFPKMivosTorYEpzz82nvk9Nl0LBj.', 'employee', 0, 0);
INSERT INTO `admin_users` (`id`, `username`, `password`, `role`, `is_blocked`, `auth_version`) VALUES (3, 'emp-26-0232', '$2b$10$p4fXqrk98ElNsaKhAXX0nOoLE3gIxb/npdp0s.KnkbTvw1l4/vm2q', 'employee', 0, 0);
INSERT INTO `admin_users` (`id`, `username`, `password`, `role`, `is_blocked`, `auth_version`) VALUES (4, 'emp-26-224', '$2b$10$4oC7FPWuNELrsqkK2v.KreXTBioT1dHaEN3DqkW835gRhBoswQb4O', 'employee', 0, 0);
INSERT INTO `admin_users` (`id`, `username`, `password`, `role`, `is_blocked`, `auth_version`) VALUES (5, 'emp-224', '$2b$10$KT9ct9lj3NHWuJ1eQ.FdxuVkCxHVWyZKK6PovqLBaeEXqM3Aqw3a2', 'employee', 0, 1);
INSERT INTO `admin_users` (`id`, `username`, `password`, `role`, `is_blocked`, `auth_version`) VALUES (6, 'emp-gwzw04', '$2b$10$Yko1v316tUDI6uf/WX985.g/AfAu1pmI.7jCySskP8QQjTClJp5my', 'employee', 0, 0);

-- Table structure for `buyer_accounts`
DROP TABLE IF EXISTS `buyer_accounts`;
CREATE TABLE `buyer_accounts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `full_name` varchar(120) NOT NULL,
  `company_name` varchar(150) DEFAULT NULL,
  `phone` varchar(30) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password` varchar(255) NOT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `reviewed_by` int DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `is_blocked` tinyint DEFAULT '0',
  `credentials_unlocked` tinyint DEFAULT '0',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `ux_buyer_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=60001;

-- Dumping data for `buyer_accounts`
INSERT INTO `buyer_accounts` (`id`, `full_name`, `company_name`, `phone`, `email`, `password`, `status`, `reviewed_by`, `reviewed_at`, `created_at`, `is_blocked`, `credentials_unlocked`) VALUES (1, 'Tahmid', 'M kings', '01601315176', 'mdmukimuddin.bd@gmail.com', '$2b$10$/uHi5pfaeFIu3on0wKyTjeHnajvGP5HBSQEQdIJom0tOqh19m2dHi', 'approved', 1, '2026-05-04 19:52:27', '2026-05-01 07:48:13', 0, 1);
INSERT INTO `buyer_accounts` (`id`, `full_name`, `company_name`, `phone`, `email`, `password`, `status`, `reviewed_by`, `reviewed_at`, `created_at`, `is_blocked`, `credentials_unlocked`) VALUES (30001, 'MD Sabbir Rahman', 'YouTube', '01326978379', 'mdsabbirrahman85984@gmail.com', '$2b$10$lsxMQXR16FLiJMQ7bwVJnujxqE82whShKP3B6q3fi6EChzjpGqOLS', 'approved', 1, '2026-05-04 20:06:34', '2026-05-02 09:27:08', 0, 1);

-- Table structure for `channels`
DROP TABLE IF EXISTS `channels`;
CREATE TABLE `channels` (
  `id` int NOT NULL AUTO_INCREMENT,
  `channel_name` varchar(255) NOT NULL,
  `channel_link` text NOT NULL,
  `is_selected` tinyint(1) DEFAULT '0',
  `whatsapp` varchar(50) DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `worker_id` int DEFAULT NULL,
  `open_date` date DEFAULT NULL,
  `sell_price` decimal(10,2) DEFAULT '0.00',
  `worker_cost` decimal(10,2) DEFAULT '0.00',
  `is_sold` tinyint(1) DEFAULT '0',
  `created_by` int DEFAULT '1',
  `gmail` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `reg_no` int DEFAULT NULL,
  `sold_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_1` (`worker_id`),
  UNIQUE KEY `channels_reg_no_key` (`reg_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1020001;

-- Dumping data for `channels`
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (6, 'Ronaldo Top fans', 'https://www.youtube.com/@ronaldotopfans-t5l', 0, NULL, '2026-04-06 01:53:25', 2, '2026-03-30 18:00:00', '257.14', '100.00', 1, 1, 'cdizymarahmanke@gmail.com', 'easypass890', 1000, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (7, 'Ronaldo Foatball king', 'https://www.youtube.com/@ronaldofoatballking', 0, NULL, '2026-04-06 01:54:01', 2, '2026-03-30 18:00:00', '266.67', '100.00', 1, 1, NULL, NULL, 1001, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (8, 'prince Ronaldo', 'https://www.youtube.com/@princeronaldo-x6o', 0, NULL, '2026-04-06 01:54:44', 2, '2026-03-30 18:00:00', '266.67', '100.00', 1, 1, NULL, NULL, 1002, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (9, 'Ronaldo brother', 'https://www.youtube.com/@tawhidprotibondi', 0, NULL, '2026-04-06 01:56:42', 3, '2026-03-30 18:00:00', '200.00', '100.00', 1, 1, 'tawhidprotibondi@gmail.com', 'mukimvai0.1', 1003, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (10, 'Ronaldo Fan', 'https://www.youtube.com/@ronaldofan-k9w', 0, NULL, '2026-04-06 01:57:22', 3, '2026-03-30 18:00:00', '200.00', '100.00', 1, 1, 'mukimmukim020@gmail.com', 'mukimvai0.1', 1004, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (11, 'Ronaldo Real', 'https://www.youtube.com/@ronaldoreal-w8c', 0, NULL, '2026-04-06 01:58:06', 3, '2026-03-31 18:00:00', '257.14', '100.00', 1, 1, 'loadingbro78@gmail.com', 'mukimvai0.1', 1005, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (30004, 'football premi', 'https://www.youtube.com/@footballpremi-c7r', 0, NULL, '2026-04-06 02:08:58', 30001, '2026-03-31 18:00:00', '257.14', '100.00', 1, 1, 'jiniman123456@gmail.com', 'jiniman11#', 1006, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (30005, 'ronaldo lover', 'https://www.youtube.com/@ronaldolover-n2e', 0, NULL, '2026-04-06 02:09:31', 30001, '2026-03-31 18:00:00', '200.00', '100.00', 1, 1, NULL, NULL, 1007, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (60002, 'Goat CR7', 'https://www.youtube.com/@goatcr7-v7', 0, NULL, '2026-04-06 02:36:03', 60001, '2026-04-04 18:00:00', '257.14', '100.00', 1, 1, 'youtuber338@gmail.com', 'YouTuber@56', 1008, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (60003, 'Ronaldo fans club', 'https://www.youtube.com/@ronaldofansclub-i5d', 0, NULL, '2026-04-06 02:37:04', 60001, '2026-04-04 18:00:00', '266.67', '100.00', 1, 1, 'ip192980@gmail.com', '99534119@abdullah', 1009, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (90001, 'Suspended', 'https://youtube.com/@bestofronaldo-t5k?si=eKVZhv987qB0-zAw', 0, NULL, '2026-04-06 05:04:24', 90001, '2026-03-29 18:00:00', '233.33', '100.00', 1, 1, NULL, NULL, 1010, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (90002, 'Suspended', 'https://youtube.com/@famousronaldofans?si=iRsM7SfiphSH7BVH', 0, NULL, '2026-04-06 05:04:49', 90001, '2026-03-29 18:00:00', '233.33', '100.00', 1, 1, NULL, NULL, 1011, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (90003, 'Suspended', 'https://youtube.com/@ronaldovideos-t7i?si=sVYa1ezfhiiysFWY', 0, NULL, '2026-04-06 05:05:12', 90001, '2026-03-29 18:00:00', '233.33', '100.00', 1, 1, NULL, NULL, 1012, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (90004, 'Suspended', 'https://youtube.com/@ronaldopictures-b4q?si=3Uy-nfyzDIcbrzoF', 0, NULL, '2026-04-06 05:06:54', 90002, '2026-03-29 18:00:00', '266.67', '100.00', 1, 1, NULL, NULL, 1013, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (90005, 'Suspended', 'https://youtube.com/@ronaldolovers-c3r?si=kcdqB6Ph-01XE0f8', 0, NULL, '2026-04-06 05:07:23', 90002, '2026-03-29 18:00:00', '266.67', '100.00', 1, 1, NULL, NULL, 1014, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (90006, 'Suspended', 'https://youtube.com/@ronaldofans-w1y?si=zlTRSMFY7c3lMywT', 0, NULL, '2026-04-06 05:07:50', 90002, '2026-03-29 18:00:00', '266.67', '100.00', 1, 1, NULL, NULL, 1015, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (180002, 'Ronaldo fanbase', 'https://www.youtube.com/@ronaldofanbase-x4z', 0, NULL, '2026-04-06 22:12:31', 180001, '2026-03-30 18:00:00', '200.00', '100.00', 1, 1, NULL, NULL, 1016, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (180003, 'Football club', 'https://www.youtube.com/@footballclub-f9q', 0, NULL, '2026-04-06 22:13:12', 180001, '2026-03-30 18:00:00', '200.00', '100.00', 1, 1, NULL, NULL, 1017, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (180004, 'ronaldo fan clud', 'https://www.youtube.com/@ronaldofanclud-j7t', 0, NULL, '2026-04-06 22:15:45', 180004, '2026-04-04 18:00:00', '257.14', '133.33', 1, 1, NULL, NULL, 1018, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (180005, 'Football Fanclud', 'https://www.youtube.com/@footballfanclud', 0, NULL, '2026-04-06 22:16:21', 180004, '2026-04-04 18:00:00', '257.14', '133.33', 1, 1, NULL, NULL, 1019, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (180006, 'CR7 Fanclud', 'https://www.youtube.com/@cr7fanclud', 0, NULL, '2026-04-06 22:16:48', 180004, '2026-04-04 18:00:00', '257.14', '133.33', 1, 1, NULL, NULL, 1020, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (270001, 'Best CR7', 'https://youtube.com/@bestcr7-z3q?si=Z591ng7Hx5zIqDyw', 1, NULL, '2026-04-14 12:48:08', 300001, '2026-04-13 18:00:00', '0.00', '0.00', 0, 3, 'abrarsaki647@gmail.com', 'New12Password', 1021, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (270002, 'Best ronaldo', 'https://youtube.com/@bestronaldo-t6h?si=R4RA1xeVhVxZgjUM', 0, NULL, '2026-04-14 12:51:08', 300001, '2026-04-13 18:00:00', '266.66', '166.67', 1, 3, 'abrarsaki22@gmail.com', 'You1 Tube1@', 1022, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (300001, 'Ronaldo star', 'https://youtube.com/@ronaldostar-f6c?si=kU63a0sY34bUjXH0', 1, NULL, '2026-04-15 02:13:28', 300001, '2026-04-13 18:00:00', '0.00', '0.00', 0, 3, 'abrarsaki33@gmail.com', 'New@Password', 1023, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (330001, 'Ronaldo club', 'https://youtube.com/@ronaldoclub-b8h?si=AqW_N3tR5rFNdJf2', 0, NULL, '2026-04-15 05:24:45', 330001, NULL, '275.00', '100.00', 1, 3, NULL, NULL, 1024, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (390001, 'Ronaldo Jr', 'https://youtube.com/@ronaldojr-k8y?si=tLSieXgIvuAesydt', 0, NULL, '2026-04-16 11:01:26', 330001, '2026-04-14 18:00:00', '275.00', '100.00', 1, 3, NULL, NULL, 1025, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (450001, 'CR7 Fan Post', 'https://youtube.com/@cr7fanpost?si=iBrOMRiww6vO5Lat', 0, NULL, '2026-04-26 01:00:19', 90001, '2026-04-20 18:00:00', '266.67', '142.86', 1, 1, 'Shajdultension@gmail.com', 'Juel25825', 1026, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (450002, 'Ronaldo Photos different part', 'https://www.youtube.com/@RonaldoPhotosdifferentpart', 0, NULL, '2026-04-26 01:02:52', 90001, '2026-04-19 18:00:00', '266.67', '142.86', 1, 1, 'dollercatch@gmail.com', 'Juel258258', 1027, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (540001, '@mychoice07', 'https://youtube.com/@mychoice07?si=Ia3bB6RaQrXcAf82', 0, NULL, '2026-04-30 02:19:51', 450001, '2026-04-29 18:00:00', '275.00', '100.00', 1, 5, 'linconabe4578045@gmail.com', 'kurigram69@', 1028, '2026-05-05 08:42:42');
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (600001, 'Ronaldo Best image on youtube', 'https://youtube.com/@ronaldobestimageonyoutube', 0, NULL, '2026-05-03 03:27:48', 90001, '2026-04-22 18:00:00', '275.00', '142.86', 1, 1, 'tanvirkhanin79@gmail.com', 'Juel258258', 1029, '2026-05-05 08:41:39');
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (600002, 'Ronaldo CR7 fan room', 'https://youtube.com/@ronaldocr7fanroom', 0, NULL, '2026-05-03 03:29:43', 90001, '2026-04-20 18:00:00', '275.00', '142.86', 1, 1, 'shadhintension@gmail.com', 'Juel25825', 1030, '2026-05-05 08:41:39');
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (630001, '@Ronaldo 008', 'https://youtube.com/@haiderali-k3g4p', 1, '01400525526', '2026-05-03 07:51:31', 450002, '2026-05-02 18:00:00', '0.00', '0.00', 0, 5, 'arafatkhangxxhcycu456@gmail.com', 'ribelali567', 1031, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (660001, '@Rolando_998', 'https://youtube.com/@rolando_998', 0, '01318909174', '2026-05-04 10:33:16', 450003, '2026-05-03 18:00:00', '0.00', '0.00', 0, 5, 'aoboaveccc@gmail.com', NULL, 1032, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (660002, '@RxNncsmkb', 'https://youtube.com/@rxnncsmkb', 0, '01869012607', '2026-05-04 10:36:45', 450004, '2026-05-03 18:00:00', '0.00', '0.00', 0, 5, 'rxnncsmkb@gmail.com', 'wrcvh@200', 1033, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (690001, '@Ronaldo_007', 'https://www.youtube.com/@Ronaldo_007-i4x', 0, '01967942113', '2026-05-04 10:55:27', 450005, '2026-05-03 18:00:00', '0.00', '0.00', 0, 5, 'bby81070', 'sbby810', 1034, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (690002, '@Ronaldo_prime', 'https://www.youtube.com/@Ronaldo_prime-f7v', 0, '01967942113', '2026-05-04 10:55:28', 450005, '2026-05-03 18:00:00', '0.00', '0.00', 0, 5, 'ukak254@gmail.com', 'ukak00700', 1035, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (720001, '@Ronaldo-46', 'https://youtube.com/@vhhdhhcnb', 0, '01788692041', '2026-05-04 11:31:48', 450006, '2026-05-03 18:00:00', '0.00', '0.00', 0, 5, 'xjhxgyjfb@gmail.com', 'miad2580', 1036, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (720002, '@Ronaldo-586', 'https://youtube.com/@jxvhfhdh', 0, '01788692041', '2026-05-04 11:31:49', 450006, '2026-05-03 18:00:00', '0.00', '0.00', 0, 5, 'mdkalhasan@gmail.com', 'miad2580', 1037, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (720003, '@Ronaldo fan-809', 'https://youtube.com/@ronaldo-35u', 0, '01788692041', '2026-05-04 11:31:49', 450006, '2026-05-03 18:00:00', '0.00', '0.00', 0, 5, 'mdhgzgdhhd@gmail.com', 'miad2580', 1038, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (750001, 'Ronaldo Fan Club', 'https://youtube.com/@ronaldofanclub-y6f', 0, NULL, '2026-05-04 12:25:02', 90001, '2026-04-20 18:00:00', '275.00', '142.86', 1, 1, 'shahinurtension@gmail.com', 'Juel25825', 1039, '2026-05-05 08:41:40');
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (780001, '@Ronaldo_fanclub-p9x', 'https://youtube.com/@ronaldo_fanclub-p9x', 0, '01332060999', '2026-05-04 20:53:23', 450007, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'asiksaiara@gmail.com', 'Atik112233', 1040, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (810001, '@MuftiAl-j5d', 'https://youtube.com/@muftial-j5d', 0, '01744693101', '2026-05-05 07:34:54', 450008, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'muftial567@gmail.com', '1234567890borno', 1041, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (840001, '@football_fantasy-p5e', 'https://youtube.com/@football_fantasy-p5e', 0, '01522102494', '2026-05-05 08:03:02', 450009, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'boyfamous240@gmail.com', '1234567890boy', 1042, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (840002, '@ronaldo0707-y2k', 'https://youtube.com/@ronaldo0707-y2k', 0, '01959473152', '2026-05-05 08:11:05', 450010, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'pedduborno@gmail.com', '123456789kgalid', 1043, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (870001, '@JajdjdUajwhwyi', 'https://youtube.com/@jajdjduajwhwyi', 0, '01868988712', '2026-05-05 10:00:19', 450011, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'rahadislam1918@gmail.com', 'Rahad1918@@', 1044, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (870002, '@FanofRonaldo-007', 'https://youtube.com/@fanofronaldo-007', 0, '01613486343', '2026-05-05 10:08:21', 450012, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'tryionlannister4@gmail.com', 'tryionjofri007', 1045, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (870003, '@Ronaldo- Fans 0884', 'https://www.youtube.com/@Ronaldo-Fans0884', 0, '01799119184', '2026-05-05 10:10:35', 450013, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'maya356ag@gmail.com', 'jim1234@A', 1046, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (870004, 'Ronaldo Fan Club', 'https://youtube.com/@ronaldofanclub-h4l', 0, '01322716595', '2026-05-05 10:10:51', 450014, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'Raifhassan6666@gmail.com', 'arafat16', 1047, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (900001, '@NayemIslam-k6p6l', 'https://youtube.com/@nayemislam-k6p6l', 0, '01305597051', '2026-05-05 10:18:27', 450015, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'NayemIslam-k6p6l', 'NayemIslam-k6p6l', 1048, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (900002, '@kingrolando07', 'https://youtube.com/@khalidkhan-j6l6t', 0, '01744693101', '2026-05-05 10:26:10', 450008, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'khalidkhan22488yy@gmail.com', '123456khalid', 1049, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (930001, '@OpuIslam-w4v', 'https://youtube.com/@opuislam-w4v', 0, '01868988712', '2026-05-05 12:29:04', 450011, '2026-05-05 18:00:00', '0.00', '0.00', 0, 5, 'Opuislam19361@gmail.com', 'rafi@@2829', 1050, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (960001, '@Ronaldo- Fans club20', 'https://www.youtube.com/@Ronaldo-Fansclub20', 0, '01799119184', '2026-05-05 12:57:52', 450013, '2026-05-05 18:00:00', '0.00', '0.00', 0, 5, 'ashikmia55ag@gmail.com', 'ashik1234@A', 1051, NULL);
INSERT INTO `channels` (`id`, `channel_name`, `channel_link`, `is_selected`, `whatsapp`, `created_at`, `worker_id`, `open_date`, `sell_price`, `worker_cost`, `is_sold`, `created_by`, `gmail`, `password`, `reg_no`, `sold_at`) VALUES (990001, 'Player Ronaldo', 'https://www.youtube.com/@playerRolando', 0, '01739263318', '2026-05-05 21:51:22', 450016, '2026-05-04 18:00:00', '0.00', '0.00', 0, 5, 'mayaislam432trjf@gmail.com', 'mamun21@', 1052, NULL);

-- Table structure for `daily_updates`
DROP TABLE IF EXISTS `daily_updates`;
CREATE TABLE `daily_updates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `channel_id` int NOT NULL,
  `shorts_uploaded` tinyint(1) DEFAULT '0',
  `sub_count` int DEFAULT '0',
  `status` enum('growing','flop','normal') DEFAULT 'growing',
  `update_date` date DEFAULT (CURRENT_DATE),
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `shorts_count` int DEFAULT '0',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_1` (`channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1200001;

-- Dumping data for `daily_updates`
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1, 60003, 0, 4, 'flop', '2026-04-05 18:00:00', '2026-04-06 02:42:05', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (2, 60002, 0, 5, 'growing', '2026-04-05 18:00:00', '2026-04-06 02:42:46', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30001, 60001, 0, 15, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:50:51', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30002, 30006, 0, 27, 'flop', '2026-04-05 18:00:00', '2026-04-06 02:51:18', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30003, 30005, 0, 143, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:51:44', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30004, 30004, 0, 83, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:52:08', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30005, 30003, 0, 14, 'flop', '2026-04-05 18:00:00', '2026-04-06 02:52:35', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30006, 30002, 0, 78, 'growing', '2026-04-05 18:00:00', '2026-04-06 02:52:59', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30007, 30001, 0, 13, 'flop', '2026-04-05 18:00:00', '2026-04-06 02:53:25', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30008, 11, 0, 85, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:53:57', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30009, 10, 0, 147, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:54:28', 11);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30010, 9, 0, 112, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:54:55', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30011, 8, 0, 42, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:55:26', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30012, 7, 0, 14, 'flop', '2026-04-05 18:00:00', '2026-04-06 02:55:43', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30013, 6, 0, 41, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:56:41', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30014, 5, 0, 13, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:57:20', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30015, 4, 0, 80, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:57:50', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30016, 3, 0, 14, 'normal', '2026-04-05 18:00:00', '2026-04-06 02:59:07', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (30017, 2, 0, 87, 'growing', '2026-04-05 18:00:00', '2026-04-06 02:59:39', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (60001, 60003, 0, 5, 'flop', '2026-04-05 18:00:00', '2026-04-06 08:58:24', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (60002, 60003, 0, 6, 'flop', '2026-04-05 18:00:00', '2026-04-06 08:59:51', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90001, 150003, 0, 6, 'flop', '2026-04-05 18:00:00', '2026-04-06 11:56:51', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90002, 150002, 0, 4, 'normal', '2026-04-05 18:00:00', '2026-04-06 11:57:24', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90003, 150001, 0, 0, 'flop', '2026-04-05 18:00:00', '2026-04-06 11:57:46', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90004, 120003, 0, 5, 'flop', '2026-04-05 18:00:00', '2026-04-06 11:59:38', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90005, 120002, 0, 7, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:00:09', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90006, 120001, 0, 4, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:00:39', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90007, 60003, 0, 5, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:01:14', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90008, 60002, 0, 16, 'growing', '2026-04-05 18:00:00', '2026-04-06 12:01:35', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90009, 60001, 0, 56, 'growing', '2026-04-05 18:00:00', '2026-04-06 12:02:14', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90010, 30006, 0, 28, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:03:22', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90011, 30006, 0, 28, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:03:29', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90012, 30005, 0, 156, 'normal', '2026-04-05 18:00:00', '2026-04-06 12:03:49', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90013, 30004, 0, 101, 'normal', '2026-04-05 18:00:00', '2026-04-06 12:04:10', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90014, 30002, 0, 79, 'growing', '2026-04-05 18:00:00', '2026-04-06 12:05:11', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90015, 30001, 0, 18, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:05:35', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90016, 30001, 0, 18, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:06:39', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90017, 8, 0, 43, 'normal', '2026-04-05 18:00:00', '2026-04-06 12:07:44', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90018, 6, 0, 41, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:08:08', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90019, 5, 0, 14, 'normal', '2026-04-05 18:00:00', '2026-04-06 12:08:41', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90020, 5, 0, 14, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:08:47', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90021, 4, 0, 83, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:09:14', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90022, 3, 0, 17, 'flop', '2026-04-05 18:00:00', '2026-04-06 12:09:34', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (90023, 2, 0, 100, 'growing', '2026-04-05 18:00:00', '2026-04-06 12:10:03', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (120001, 180006, 0, 63, 'growing', '2026-04-06 18:00:00', '2026-04-06 23:37:37', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (120002, 180005, 0, 59, 'growing', '2026-04-06 18:00:00', '2026-04-06 23:37:55', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (120003, 180004, 0, 65, 'growing', '2026-04-06 18:00:00', '2026-04-06 23:38:21', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (120004, 180003, 0, 142, 'normal', '2026-04-06 18:00:00', '2026-04-06 23:38:44', 15);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (120005, 180002, 0, 173, 'normal', '2026-04-06 18:00:00', '2026-04-06 23:39:07', 15);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (120006, 180001, 0, 95, 'normal', '2026-04-06 18:00:00', '2026-04-06 23:39:30', 13);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (120007, 180001, 0, 95, 'flop', '2026-04-06 18:00:00', '2026-04-06 23:39:36', 13);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (150001, 180006, 0, 77, 'normal', '2026-04-06 18:00:00', '2026-04-07 12:40:00', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (150002, 180005, 0, 70, 'normal', '2026-04-06 18:00:00', '2026-04-07 12:40:49', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (150003, 180004, 0, 74, 'flop', '2026-04-06 18:00:00', '2026-04-07 12:41:26', 0);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180001, 180006, 0, 139, 'growing', '2026-04-07 18:00:00', '2026-04-08 11:32:44', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180002, 180005, 0, 174, 'growing', '2026-04-07 18:00:00', '2026-04-08 11:33:08', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180003, 180004, 0, 102, 'flop', '2026-04-07 18:00:00', '2026-04-08 11:33:30', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180004, 60003, 0, 101, 'growing', '2026-04-07 18:00:00', '2026-04-08 11:33:57', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180005, 60002, 0, 51, 'normal', '2026-04-07 18:00:00', '2026-04-08 11:34:11', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180006, 30006, 0, 28, 'flop', '2026-04-07 18:00:00', '2026-04-08 11:35:03', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180007, 30004, 0, 223, 'growing', '2026-04-07 18:00:00', '2026-04-08 11:35:22', 14);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180008, 30001, 0, 63, 'flop', '2026-04-07 18:00:00', '2026-04-08 11:36:46', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180009, 30001, 0, 18, 'normal', '2026-04-07 18:00:00', '2026-04-08 11:36:50', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180010, 11, 0, 127, 'normal', '2026-04-07 18:00:00', '2026-04-08 11:37:21', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180011, 8, 0, 43, 'normal', '2026-04-07 18:00:00', '2026-04-08 11:37:53', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180012, 8, 0, 43, 'flop', '2026-04-07 18:00:00', '2026-04-08 11:37:57', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180013, 7, 0, 14, 'flop', '2026-04-07 18:00:00', '2026-04-08 11:38:15', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (180014, 6, 0, 95, 'flop', '2026-04-07 18:00:00', '2026-04-08 11:38:32', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (210001, 180006, 0, 143, 'growing', '2026-04-08 18:00:00', '2026-04-08 22:15:30', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240001, 180006, 0, 148, 'normal', '2026-04-08 18:00:00', '2026-04-09 02:21:39', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240002, 180006, 0, 148, 'growing', '2026-04-08 18:00:00', '2026-04-09 02:21:46', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240003, 180005, 0, 186, 'growing', '2026-04-08 18:00:00', '2026-04-09 02:22:07', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240004, 180004, 0, 114, 'flop', '2026-04-08 18:00:00', '2026-04-09 02:22:25', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240005, 60003, 0, 113, 'flop', '2026-04-08 18:00:00', '2026-04-09 02:22:44', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240006, 60003, 0, 113, 'flop', '2026-04-08 18:00:00', '2026-04-09 02:23:09', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240007, 60002, 0, 51, 'flop', '2026-04-08 18:00:00', '2026-04-09 02:23:22', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240008, 30004, 0, 242, 'growing', '2026-04-08 18:00:00', '2026-04-09 02:24:23', 14);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240009, 30004, 0, 242, 'growing', '2026-04-08 18:00:00', '2026-04-09 02:24:34', 15);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240010, 30001, 0, 71, 'normal', '2026-04-08 18:00:00', '2026-04-09 02:25:55', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240011, 11, 0, 161, 'normal', '2026-04-08 18:00:00', '2026-04-09 02:27:19', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240012, 7, 0, 15, 'flop', '2026-04-08 18:00:00', '2026-04-09 02:27:41', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (240013, 6, 0, 101, 'flop', '2026-04-08 18:00:00', '2026-04-09 02:27:55', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (270001, 30006, 0, 79, 'normal', '2026-04-08 18:00:00', '2026-04-09 10:14:32', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (270002, 30004, 0, 265, 'growing', '2026-04-08 18:00:00', '2026-04-09 10:16:23', 17);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (300001, 180006, 0, 205, 'growing', '2026-04-08 18:00:00', '2026-04-09 10:22:48', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (300002, 180005, 0, 313, 'growing', '2026-04-08 18:00:00', '2026-04-09 10:23:10', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (300003, 180004, 0, 125, 'flop', '2026-04-08 18:00:00', '2026-04-09 10:23:32', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (300004, 30004, 0, 266, 'growing', '2026-04-08 18:00:00', '2026-04-09 10:24:54', 17);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (300005, 11, 0, 192, 'normal', '2026-04-08 18:00:00', '2026-04-09 10:25:39', 16);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330001, 180006, 0, 226, 'growing', '2026-04-09 18:00:00', '2026-04-09 20:13:05', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330002, 180005, 0, 383, 'growing', '2026-04-09 18:00:00', '2026-04-09 20:13:23', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330003, 180004, 0, 191, 'normal', '2026-04-09 18:00:00', '2026-04-09 20:13:47', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330004, 60003, 0, 113, 'flop', '2026-04-09 18:00:00', '2026-04-09 20:14:10', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330005, 60002, 0, 82, 'flop', '2026-04-09 18:00:00', '2026-04-09 20:14:27', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330006, 30006, 0, 82, 'flop', '2026-04-09 18:00:00', '2026-04-09 20:14:48', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330007, 30004, 0, 265, 'growing', '2026-04-09 18:00:00', '2026-04-09 20:15:00', 17);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330008, 11, 0, 198, 'normal', '2026-04-09 18:00:00', '2026-04-09 20:15:47', 16);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330009, 8, 0, 45, 'flop', '2026-04-09 18:00:00', '2026-04-09 20:16:08', 0);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330010, 8, 0, 45, 'flop', '2026-04-09 18:00:00', '2026-04-09 20:16:15', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330011, 7, 0, 20, 'flop', '2026-04-09 18:00:00', '2026-04-09 20:16:33', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (330012, 6, 0, 128, 'flop', '2026-04-09 18:00:00', '2026-04-09 20:16:53', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360001, 180006, 0, 314, 'growing', '2026-04-09 18:00:00', '2026-04-10 12:17:51', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360002, 180006, 0, 314, 'growing', '2026-04-09 18:00:00', '2026-04-10 12:17:52', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360003, 180005, 0, 591, 'growing', '2026-04-09 18:00:00', '2026-04-10 12:18:09', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360004, 180004, 0, 250, 'normal', '2026-04-09 18:00:00', '2026-04-10 12:18:25', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360005, 180004, 0, 250, 'normal', '2026-04-09 18:00:00', '2026-04-10 12:18:25', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360006, 60002, 0, 129, 'flop', '2026-04-09 18:00:00', '2026-04-10 12:19:10', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360007, 30004, 0, 270, 'growing', '2026-04-09 18:00:00', '2026-04-10 12:19:36', 17);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360008, 11, 0, 202, 'normal', '2026-04-09 18:00:00', '2026-04-10 12:20:03', 16);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360009, 8, 0, 68, 'flop', '2026-04-09 18:00:00', '2026-04-10 12:20:24', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360010, 7, 0, 60, 'flop', '2026-04-09 18:00:00', '2026-04-10 12:20:37', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (360011, 6, 0, 280, 'flop', '2026-04-09 18:00:00', '2026-04-10 12:21:16', 14);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390001, 180006, 0, 342, 'growing', '2026-04-10 18:00:00', '2026-04-11 01:43:03', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390002, 180005, 0, 636, 'growing', '2026-04-10 18:00:00', '2026-04-11 01:43:23', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390003, 180004, 0, 267, 'normal', '2026-04-10 18:00:00', '2026-04-11 01:43:37', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390004, 60003, 0, 129, 'normal', '2026-04-10 18:00:00', '2026-04-11 01:44:09', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390005, 60002, 0, 205, 'growing', '2026-04-10 18:00:00', '2026-04-11 01:45:08', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390006, 30004, 0, 268, 'growing', '2026-04-10 18:00:00', '2026-04-11 01:45:33', 17);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390007, 11, 0, 227, 'normal', '2026-04-10 18:00:00', '2026-04-11 01:46:01', 18);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390008, 6, 0, 364, 'growing', '2026-04-10 18:00:00', '2026-04-11 01:46:27', 14);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390009, 7, 0, 81, 'flop', '2026-04-10 18:00:00', '2026-04-11 01:46:41', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (390010, 8, 0, 69, 'flop', '2026-04-10 18:00:00', '2026-04-11 01:46:51', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (420001, 240001, 0, 14, 'normal', '2026-04-13 18:00:00', '2026-04-14 10:38:38', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (450001, 270001, 0, 2, 'normal', '2026-04-13 18:00:00', '2026-04-14 12:49:45', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (450002, 270002, 0, 3, 'normal', '2026-04-13 18:00:00', '2026-04-14 12:51:42', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (480001, 300001, 0, 8, 'growing', '2026-04-14 18:00:00', '2026-04-15 02:14:00', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (480002, 270001, 0, 14, 'growing', '2026-04-14 18:00:00', '2026-04-15 02:15:11', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (510001, 270001, 0, 22, 'normal', '2026-04-14 18:00:00', '2026-04-15 11:15:14', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (510002, 270002, 0, 3, 'flop', '2026-04-14 18:00:00', '2026-04-15 11:15:30', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (510003, 300001, 0, 11, 'normal', '2026-04-14 18:00:00', '2026-04-15 11:15:47', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (510004, 330001, 0, 13, 'normal', '2026-04-14 18:00:00', '2026-04-15 11:16:03', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (510005, 360001, 0, 10, 'normal', '2026-04-14 18:00:00', '2026-04-15 11:16:22', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (510006, 360002, 0, 1, 'flop', '2026-04-14 18:00:00', '2026-04-15 11:16:36', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (540001, 390001, 0, 54, 'growing', '2026-04-15 18:00:00', '2026-04-16 11:01:58', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (540002, 330001, 0, 67, 'growing', '2026-04-15 18:00:00', '2026-04-16 11:02:27', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (570001, 390001, 0, 67, 'growing', '2026-04-16 18:00:00', '2026-04-17 01:06:30', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (570002, 390001, 0, 67, 'normal', '2026-04-16 18:00:00', '2026-04-17 01:06:40', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (570003, 360002, 0, 94, 'normal', '2026-04-16 18:00:00', '2026-04-17 01:06:56', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (570004, 360001, 0, 82, 'normal', '2026-04-16 18:00:00', '2026-04-17 01:07:13', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (570005, 330001, 0, 243, 'growing', '2026-04-16 18:00:00', '2026-04-17 01:07:46', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (570006, 270002, 0, 21, 'flop', '2026-04-16 18:00:00', '2026-04-17 01:08:05', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (570007, 270001, 0, 32, 'normal', '2026-04-16 18:00:00', '2026-04-17 01:08:19', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (600001, 420001, 0, 75, 'normal', '2026-04-18 18:00:00', '2026-04-19 06:48:56', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (600002, 390001, 0, 150, 'normal', '2026-04-18 18:00:00', '2026-04-19 06:49:23', 9);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (600003, 360002, 0, 123, 'normal', '2026-04-18 18:00:00', '2026-04-19 06:49:52', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (600004, 360001, 0, 261, 'normal', '2026-04-18 18:00:00', '2026-04-19 06:50:08', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (600005, 330001, 0, 472, 'growing', '2026-04-18 18:00:00', '2026-04-19 06:50:25', 9);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (600006, 270002, 0, 34, 'flop', '2026-04-18 18:00:00', '2026-04-19 06:50:42', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (600007, 270001, 0, 34, 'normal', '2026-04-18 18:00:00', '2026-04-19 06:50:57', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (630001, 300001, 0, 59, 'normal', '2026-04-24 18:00:00', '2026-04-24 23:29:42', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (630002, 270002, 0, 178, 'growing', '2026-04-24 18:00:00', '2026-04-24 23:30:06', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (630003, 270001, 0, 72, 'normal', '2026-04-24 18:00:00', '2026-04-24 23:30:33', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (660001, 450002, 0, 226, 'normal', '2026-04-25 18:00:00', '2026-04-26 01:03:58', 14);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (660002, 450001, 0, 243, 'normal', '2026-04-25 18:00:00', '2026-04-26 01:04:29', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (690001, 480001, 0, 56, 'normal', '2026-04-28 18:00:00', '2026-04-29 12:48:55', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (720001, 480001, 0, 56, 'flop', '2026-04-28 18:00:00', '2026-04-29 13:14:47', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (750001, 540001, 0, 12, 'growing', '2026-04-29 18:00:00', '2026-04-30 02:27:43', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (780001, 270001, 0, 99, 'flop', '2026-04-29 18:00:00', '2026-04-30 12:51:07', 18);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (780002, 300001, 0, 135, 'flop', '2026-04-29 18:00:00', '2026-04-30 12:51:34', 18);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (780003, 540001, 0, 33, 'normal', '2026-04-29 18:00:00', '2026-04-30 12:51:45', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (810001, 540001, 0, 57, 'growing', '2026-04-30 18:00:00', '2026-05-01 11:23:55', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (840001, 540001, 0, 108, 'normal', '2026-05-01 18:00:00', '2026-05-02 12:49:13', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (870001, 270001, 0, 119, 'flop', '2026-05-02 18:00:00', '2026-05-03 03:30:32', 20);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (870002, 300001, 0, 155, 'flop', '2026-05-02 18:00:00', '2026-05-03 03:30:44', 20);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (870003, 540001, 0, 138, 'normal', '2026-05-02 18:00:00', '2026-05-03 03:30:59', 8);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (870004, 600001, 0, 191, 'normal', '2026-05-02 18:00:00', '2026-05-03 03:31:17', 16);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (870005, 600002, 0, 219, 'normal', '2026-05-02 18:00:00', '2026-05-03 03:31:34', 18);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900001, 540001, 0, 154, 'normal', '2026-05-03 18:00:00', '2026-05-03 21:28:45', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900002, 540001, 0, 154, 'normal', '2026-05-03 18:00:00', '2026-05-03 21:28:46', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900003, 540001, 0, 154, 'normal', '2026-05-03 18:00:00', '2026-05-03 21:28:46', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900004, 540001, 0, 154, 'normal', '2026-05-03 18:00:00', '2026-05-03 21:28:46', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900005, 540001, 0, 154, 'normal', '2026-05-03 18:00:00', '2026-05-03 21:28:47', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900006, 540001, 0, 154, 'normal', '2026-05-03 18:00:00', '2026-05-03 21:28:47', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900007, 630001, 0, 27, 'growing', '2026-05-03 18:00:00', '2026-05-03 21:29:42', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900008, 630001, 0, 27, 'growing', '2026-05-03 18:00:00', '2026-05-03 21:29:43', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (900009, 630001, 0, 27, 'normal', '2026-05-03 18:00:00', '2026-05-03 21:29:54', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (930001, 720002, 0, 16, 'flop', '2026-05-03 18:00:00', '2026-05-04 12:49:06', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (930002, 720002, 0, 16, 'flop', '2026-05-03 18:00:00', '2026-05-04 12:49:06', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (930003, 720002, 0, 16, 'flop', '2026-05-03 18:00:00', '2026-05-04 12:49:06', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (930004, 720002, 0, 16, 'flop', '2026-05-03 18:00:00', '2026-05-04 12:49:06', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (960001, 600001, 0, 246, 'normal', '2026-05-03 18:00:00', '2026-05-04 12:59:20', 16);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (960002, 540001, 0, 190, 'normal', '2026-05-03 18:00:00', '2026-05-04 13:01:21', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (960003, 630001, 0, 55, 'normal', '2026-05-03 18:00:00', '2026-05-04 13:01:56', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (960004, 660001, 0, 3, 'flop', '2026-05-03 18:00:00', '2026-05-04 13:03:43', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (960005, 660002, 0, 11, 'flop', '2026-05-03 18:00:00', '2026-05-04 13:04:33', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (960006, 690001, 0, 13, 'flop', '2026-05-03 18:00:00', '2026-05-04 13:04:54', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (960007, 720003, 0, 5, 'growing', '2026-05-03 18:00:00', '2026-05-04 13:05:27', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (990001, 750001, 0, 191, 'normal', '2026-05-04 18:00:00', '2026-05-04 19:34:46', 22);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (990002, 540001, 0, 197, 'normal', '2026-05-04 18:00:00', '2026-05-04 20:01:45', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (990003, 750001, 0, 191, 'normal', '2026-05-04 18:00:00', '2026-05-04 20:08:55', 22);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020001, 630001, 0, 101, 'normal', '2026-05-04 18:00:00', '2026-05-05 11:26:48', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020002, 660001, 0, 71, 'flop', '2026-05-04 18:00:00', '2026-05-05 11:29:23', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020003, 660001, 0, 71, 'normal', '2026-05-04 18:00:00', '2026-05-05 11:29:48', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020004, 660002, 0, 54, 'flop', '2026-05-04 18:00:00', '2026-05-05 11:30:06', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020005, 690001, 0, 57, 'flop', '2026-05-04 18:00:00', '2026-05-05 11:30:23', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020006, 690002, 0, 37, 'normal', '2026-05-04 18:00:00', '2026-05-05 11:31:12', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020007, 720001, 0, 24, 'growing', '2026-05-04 18:00:00', '2026-05-05 11:31:42', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020008, 690001, 0, 57, 'normal', '2026-05-04 18:00:00', '2026-05-05 11:32:19', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020009, 660002, 0, 54, 'normal', '2026-05-04 18:00:00', '2026-05-05 11:32:31', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020010, 720003, 0, 52, 'normal', '2026-05-04 18:00:00', '2026-05-05 11:33:25', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1020011, 720002, 0, 41, 'flop', '2026-05-04 18:00:00', '2026-05-05 11:33:50', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1050001, 270001, 0, 141, 'flop', '2026-05-04 18:00:00', '2026-05-05 14:11:45', 24);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1050002, 630001, 0, 170, 'flop', '2026-05-04 18:00:00', '2026-05-05 14:12:11', 24);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1050003, 300001, 0, 170, 'flop', '2026-05-04 18:00:00', '2026-05-05 14:12:41', 24);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1050004, 630001, 0, 104, 'flop', '2026-05-04 18:00:00', '2026-05-05 14:13:18', 10);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1050005, 660001, 0, 69, 'normal', '2026-05-04 18:00:00', '2026-05-05 14:13:47', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1050006, 660002, 0, 61, 'normal', '2026-05-04 18:00:00', '2026-05-05 14:14:05', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1080001, 990001, 0, 37, 'flop', '2026-05-05 18:00:00', '2026-05-05 23:21:04', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1080002, 990001, 0, 37, 'normal', '2026-05-05 18:00:00', '2026-05-05 23:21:05', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1080003, 960001, 0, 8, 'flop', '2026-05-05 18:00:00', '2026-05-05 23:23:35', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1080004, 930001, 0, 12, 'flop', '2026-05-05 18:00:00', '2026-05-05 23:24:09', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1080005, 900002, 0, 8, 'flop', '2026-05-05 18:00:00', '2026-05-05 23:24:26', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1110001, 900001, 0, 46, 'normal', '2026-05-05 18:00:00', '2026-05-05 23:48:28', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1110002, 870004, 0, 144, 'growing', '2026-05-05 18:00:00', '2026-05-05 23:48:56', 2);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1110003, 870003, 0, 214, 'growing', '2026-05-05 18:00:00', '2026-05-05 23:49:10', 24);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1110004, 870004, 0, 19, 'flop', '2026-05-05 18:00:00', '2026-05-05 23:49:20', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140001, 720002, 0, 49, 'normal', '2026-05-05 18:00:00', '2026-05-05 23:55:05', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140002, 630001, 0, 112, 'normal', '2026-05-05 18:00:00', '2026-05-05 23:57:38', 12);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140003, 660001, 0, 69, 'normal', '2026-05-05 18:00:00', '2026-05-05 23:59:46', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140004, 660002, 0, 92, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:00:14', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140005, 690001, 0, 58, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:00:40', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140006, 690002, 0, 37, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:01:20', 3);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140007, 720001, 0, 42, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:01:44', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140008, 720001, 0, 42, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:02:02', 5);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140009, 720002, 0, 49, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:02:21', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140010, 780001, 0, 78, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:02:42', 6);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140011, 810001, 0, 53, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:03:26', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140012, 840001, 0, 39, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:03:46', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140013, 840002, 0, 14, 'flop', '2026-05-05 18:00:00', '2026-05-06 00:04:26', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140014, 870001, 0, 38, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:05:06', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140015, 870002, 0, 27, 'flop', '2026-05-05 18:00:00', '2026-05-06 00:05:41', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140016, 870003, 0, 16, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:06:55', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140017, 870004, 0, 21, 'flop', '2026-05-05 18:00:00', '2026-05-06 00:07:52', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140018, 900001, 0, 47, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:08:08', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1140019, 990001, 0, 40, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:08:34', 4);
INSERT INTO `daily_updates` (`id`, `channel_id`, `shorts_uploaded`, `sub_count`, `status`, `update_date`, `created_at`, `shorts_count`) VALUES (1170001, 990001, 0, 43, 'normal', '2026-05-05 18:00:00', '2026-05-06 00:21:58', 4);

-- Table structure for `employee_applications`
DROP TABLE IF EXISTS `employee_applications`;
CREATE TABLE `employee_applications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `full_name` varchar(120) NOT NULL,
  `phone` varchar(30) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password` varchar(255) NOT NULL,
  `work_preference` enum('online','field','hybrid') NOT NULL DEFAULT 'hybrid',
  `job_reference` varchar(80) DEFAULT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `reviewed_by` int DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_admin_id` int DEFAULT NULL,
  `assigned_username` varchar(50) DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_employee_apps_status` (`status`),
  KEY `idx_employee_apps_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001;

-- Dumping data for `employee_applications`
INSERT INTO `employee_applications` (`id`, `full_name`, `phone`, `email`, `password`, `work_preference`, `job_reference`, `status`, `reviewed_by`, `reviewed_at`, `created_admin_id`, `assigned_username`, `created_at`) VALUES (1, 'Mukim', '01601315176', 'mdmukimuddin.bd@gmail.com', '$2b$10$Yko1v316tUDI6uf/WX985.g/AfAu1pmI.7jCySskP8QQjTClJp5my', 'hybrid', 'channel-sourcing-field-ytm', 'approved', 1, '2026-05-01 23:48:15', 6, 'emp-gwzw04', '2026-05-01 23:45:19');

-- Table structure for `employee_details`
DROP TABLE IF EXISTS `employee_details`;
CREATE TABLE `employee_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `father_name` varchar(100) DEFAULT NULL,
  `mother_name` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `present_address` text DEFAULT NULL,
  `permanent_address` text DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `nid_no` varchar(50) DEFAULT NULL,
  `joining_date` date DEFAULT NULL,
  `designation` varchar(50) DEFAULT NULL,
  `basic_salary` decimal(10,2) DEFAULT NULL,
  `bank_name` varchar(100) DEFAULT NULL,
  `account_no` varchar(50) DEFAULT NULL,
  `emergency_contact_name` varchar(100) DEFAULT NULL,
  `emergency_contact_relation` varchar(50) DEFAULT NULL,
  `emergency_contact_phone` varchar(20) DEFAULT NULL,
  `contract_target` int DEFAULT '0',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `admin_id` (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=450001;

-- Dumping data for `employee_details`
INSERT INTO `employee_details` (`id`, `admin_id`, `full_name`, `father_name`, `mother_name`, `phone`, `email`, `present_address`, `permanent_address`, `dob`, `nid_no`, `joining_date`, `designation`, `basic_salary`, `bank_name`, `account_no`, `emergency_contact_name`, `emergency_contact_relation`, `emergency_contact_phone`, `contract_target`) VALUES (1, 1, 'Tahmid', NULL, NULL, '01601315176', 'riftolifebd@gmail.com', '32/1, Madrasa Road, Auchpara, Tongi, Gazipur.', '10E, Madani Garden', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO `employee_details` (`id`, `admin_id`, `full_name`, `father_name`, `mother_name`, `phone`, `email`, `present_address`, `permanent_address`, `dob`, `nid_no`, `joining_date`, `designation`, `basic_salary`, `bank_name`, `account_no`, `emergency_contact_name`, `emergency_contact_relation`, `emergency_contact_phone`, `contract_target`) VALUES (90001, 2, 'Tahmid', NULL, NULL, '01601315176', 'riftolifebd@gmail.com', '32/1, Madrasa Road, Auchpara, Tongi, Gazipur', '10E, Madani Garden', NULL, NULL, NULL, NULL, '10000.00', NULL, NULL, NULL, NULL, NULL, 300);
INSERT INTO `employee_details` (`id`, `admin_id`, `full_name`, `father_name`, `mother_name`, `phone`, `email`, `present_address`, `permanent_address`, `dob`, `nid_no`, `joining_date`, `designation`, `basic_salary`, `bank_name`, `account_no`, `emergency_contact_name`, `emergency_contact_relation`, `emergency_contact_phone`, `contract_target`) VALUES (90002, 3, 'Abdullah sharkar', NULL, NULL, '01862303317', 'abdullahsharkar86@gmail.com', NULL, NULL, '2009-07-09 17:00:00', NULL, '2026-04-13 18:00:00', 'Client Acquisition & Channel Development Executive', '3500.00', NULL, NULL, NULL, NULL, NULL, 100);
INSERT INTO `employee_details` (`id`, `admin_id`, `full_name`, `father_name`, `mother_name`, `phone`, `email`, `present_address`, `permanent_address`, `dob`, `nid_no`, `joining_date`, `designation`, `basic_salary`, `bank_name`, `account_no`, `emergency_contact_name`, `emergency_contact_relation`, `emergency_contact_phone`, `contract_target`) VALUES (180001, 4, 'Mahi islam ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-14 18:00:00', 'Client Acquisition & Channel Development Executive', '4000.00', NULL, NULL, NULL, NULL, NULL, 100);
INSERT INTO `employee_details` (`id`, `admin_id`, `full_name`, `father_name`, `mother_name`, `phone`, `email`, `present_address`, `permanent_address`, `dob`, `nid_no`, `joining_date`, `designation`, `basic_salary`, `bank_name`, `account_no`, `emergency_contact_name`, `emergency_contact_relation`, `emergency_contact_phone`, `contract_target`) VALUES (270001, 5, 'Md Rubel Abedin', NULL, NULL, '+880 1625-191269', 'rubelabedin3@gmail.com', 'Home/Holding:020700, Vill: Miapara, Post: Kurigram-5600, Kurigram Paurashava, Kurigram District, Kurigram', 'Home/Holding:020700, Vill: Miapara, Post: Kurigram-5600, Kurigram Paurashava, Kurigram District, Kurigram', '1993-09-09 18:00:00', '19934925209000079', '2026-04-29 18:00:00', 'Channel Sourcing Executive ', '25000.00', NULL, NULL, '01310319429', 'Sister', '01310319429', 600);
INSERT INTO `employee_details` (`id`, `admin_id`, `full_name`, `father_name`, `mother_name`, `phone`, `email`, `present_address`, `permanent_address`, `dob`, `nid_no`, `joining_date`, `designation`, `basic_salary`, `bank_name`, `account_no`, `emergency_contact_name`, `emergency_contact_relation`, `emergency_contact_phone`, `contract_target`) VALUES (360001, 6, 'Mukim', NULL, NULL, '01601315176', 'mdmukimuddin.bd@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);

-- Table structure for `login_attempts`
DROP TABLE IF EXISTS `login_attempts`;
CREATE TABLE `login_attempts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ip` varchar(45) NOT NULL,
  `attempts` int DEFAULT '1',
  `last_attempt` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `ip` (`ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=570001;


-- Table structure for `sources`
DROP TABLE IF EXISTS `sources`;
CREATE TABLE `sources` (
  `id` int NOT NULL AUTO_INCREMENT,
  `caption` text DEFAULT NULL,
  `audio` text DEFAULT NULL,
  `link` text DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=90001;

-- Dumping data for `sources`
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (1, 'Audio 1', 'audio', 'https://youtube.com/source/eTxGfdrTZSE/shorts?si=f5QsqSF6z8BAdJW-', '2026-04-08 22:00:21');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (2, 'Audio 2', 'audio', 'https://youtube.com/source/AAVzWdPinV8/shorts?si=W9pag3lJYof0WuMO', '2026-04-08 22:01:28');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (3, 'Audio 3', 'audio', 'https://youtube.com/source/NT4eF9YsYnM/shorts?si=ChlJ0hdUFKH6MvPi', '2026-04-08 22:01:42');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (4, 'Audio 4', 'audio', 'https://www.youtube.com/source/WsCuPOfRgMI/shorts?si=_GcspSqAw1yTANB5', '2026-04-08 22:01:56');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (5, 'Audio 5', 'audio', 'https://www.youtube.com/source/Kcj5-jWxgKs/shorts?si=1J56EMqukWweUljO', '2026-04-08 22:02:09');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (7, 'Caption 1', 'caption', 'Ronaldo against Georgia  #ronaldo  #shorts #football#cristianoronaldo#edit#cr7👑🗿 #viralvideo.,', '2026-04-08 22:03:33');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (8, 'Caption 2', 'caption', 'কত সুন্দর ছবি তাই না#puzzle  #illustration  #youtubeshorts#yoursakib#facts  #football  #vaoral video#facts', '2026-04-08 22:04:48');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (9, 'Audio 6', 'audio', 'https://youtube.com/source/Cozx50UrdH0/shorts?si=bHQ9ydzlqC7jwgso', '2026-04-08 22:05:08');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (30001, 'Audio 7', 'audio', 'https://www.youtube.com/source/bEYiPCbHAtM/shorts?bp=8gUeChwSGgoLYkVZaVBDYkhBdE0SC2JFWWlQQ2JIQXRN', '2026-04-23 08:19:38');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (30002, 'Audio 8', 'audio', 'https://www.youtube.com/source/i40xsDsZQUI/shorts?bp=8gUeChwSGgoLaTQweHNEc1pRVUkSC2k0MHhzRHNaUVVJ', '2026-04-23 08:19:51');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (30003, 'Audio 9', 'audio', 'https://www.youtube.com/source/mAoaXW5-Na8/shorts?bp=8gUeChwSGgoLbUFvYVhXNS1OYTgSC21Bb2FYVzUtTmE4', '2026-04-23 08:20:03');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (30004, 'Audio 10', 'audio', 'https://www.youtube.com/source/zeKCzmAKKP4/shorts?bp=8gUeChwSGgoLemVLQ3ptQUtLUDQSC3plS0N6bUFLS1A0', '2026-04-23 08:20:20');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (30005, 'Audio 11', 'audio', 'https://www.youtube.com/source/rngLO3tF2mA/shorts?bp=8gUeChwSGgoLcm5nTE8zdEYybUESC3JuZ0xPM3RGMm1B', '2026-04-23 08:20:52');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (60001, 'Caption 3', 'caption', '#junior neymar against# neymar#shorts #football#juniorneymar #edit#top10 junior neymar #viralvideo💥⚽', '2026-04-29 13:26:25');
INSERT INTO `sources` (`id`, `caption`, `audio`, `link`, `created_at`) VALUES (60002, 'Caption 4', 'caption', '#Leo messi against #messi#shorts #football#goatmessi #edit#top10leo #viralvideo💥⚽', '2026-04-29 13:26:51');

-- Table structure for `workers`
DROP TABLE IF EXISTS `workers`;
CREATE TABLE `workers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `whatsapp` varchar(50) DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_worker_creator` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=810001;

-- Dumping data for `workers`
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (1, 'Fida ', '+880 1867-255439', '2026-04-06 01:34:02', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (2, 'Emran Faisal', '+880 1892-358061', '2026-04-06 01:52:46', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (3, 'Ali Akber Rafi', '+880 1774-837331', '2026-04-06 01:55:24', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (4, 'Shuvo Chandra', '+880 1954-391566', '2026-04-06 01:58:36', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (30001, 'Bayejid', '+880 1810-933126', '2026-04-06 02:07:59', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (60001, 'Abdullah Sharker babu', '+880 1862-303317', '2026-04-06 02:34:46', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (90001, 'Juwel Rana', '+880 1724-960049', '2026-04-06 05:01:37', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (90002, 'Raian Rahat', '+880 1310-548590', '2026-04-06 05:02:01', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (120003, 'Jaber', '01829692328', '2026-04-06 08:45:01', 2);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (150001, 'Anas', '01865301008', '2026-04-06 09:10:55', 2);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (180001, 'Shifat hasan', '+880 1796-005396', '2026-04-06 22:10:14', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (180004, 'Juhin', '+880 1606-100151', '2026-04-06 22:14:24', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (210001, 'Shahadat Ornob', '+880 1715-737711', '2026-04-07 00:23:43', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (210002, 'Tanjida Wahid Bushra', '+880 1762-871565', '2026-04-07 00:25:01', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (210003, 'Rafi Samnan', '+880 1326-967822', '2026-04-07 00:26:50', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (240001, 'Single boy', '+880 1810-933126', '2026-04-14 10:00:56', 2);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (270001, 'John Doe', '+880 1796-005396', '2026-04-14 10:36:02', 2);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (300001, 'Abrar', '+880 1757-333152', '2026-04-14 12:45:59', 3);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (330001, 'abir', NULL, '2026-04-15 05:24:10', 3);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (360001, 'Mahi ', '+880 1721-138324', '2026-04-15 11:08:28', 1);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (390001, 'karim', 'jnmmbvb', '2026-04-29 12:46:33', 2);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (420001, 'abdullah', '+880 1796-005396', '2026-04-29 13:13:32', 2);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450001, 'Rubel', '01625191269', '2026-04-30 02:09:13', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450002, 'Yasin Arafat', '01400525526', '2026-05-03 07:51:30', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450003, 'Md Maruf islam', '01318909174', '2026-05-04 10:33:15', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450004, 'Riyad', '01869012607', '2026-05-04 10:36:44', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450005, 'Biplob hasan', '01967942113', '2026-05-04 10:55:26', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450006, 'Miad', '01788692041', '2026-05-04 11:31:47', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450007, 'Md Iqbal Hasan Atik', '01332060999', '2026-05-04 20:53:22', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450008, 'Abdullah Al Mahin', '01744693101', '2026-05-05 07:34:53', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450009, 'Billah', '01522102494', '2026-05-05 08:03:01', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450010, 'Khalid hasan', '01959473152', '2026-05-05 08:11:04', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450011, 'Rahad', '01868988712', '2026-05-05 10:00:18', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450012, 'Hossain Mohammad hamja Ridom', '01613486343', '2026-05-05 10:08:20', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450013, 'Md Jim Ahmed', '01799119184', '2026-05-05 10:10:34', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450014, 'Arafat', '01322716595', '2026-05-05 10:10:49', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450015, 'Nayim islam', '01305597051', '2026-05-05 10:18:26', 5);
INSERT INTO `workers` (`id`, `name`, `whatsapp`, `created_at`, `created_by`) VALUES (450016, 'Md  Mehedi Hasan Mamun', '01739263318', '2026-05-05 21:51:21', 5);

SET FOREIGN_KEY_CHECKS = 1;
