import mysql from 'mysql2/promise';
import fs from 'fs';
import path from 'path';

// Load .env manually to avoid extra dependencies
function getEnv(key) {
  try {
    const envPath = path.join(process.cwd(), '.env');
    if (fs.existsSync(envPath)) {
      const env = fs.readFileSync(envPath, 'utf8');
      const lines = env.split('\n');
      for (const line of lines) {
        const [k, v] = line.split('=');
        if (k === key) return v.trim();
      }
    }
  } catch (e) {}
  return null;
}

const DATABASE_URL = getEnv('DATABASE_URL') || 'mysql://SW62n4S6YfW5wSz.root:vvY0htEqzqbGuDJH@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslaccept=accept_invalid_certs';

async function extract() {
  console.log('Connecting to database...');
  const connection = await mysql.createConnection({
    uri: DATABASE_URL,
    ssl: DATABASE_URL.includes('tidbcloud') ? {
      minVersion: 'TLSv1.2',
      rejectUnauthorized: true
    } : undefined
  });
  console.log('Connected successfully');

  const [tables] = await connection.query('SHOW TABLES');
  const tableNames = tables.map(t => Object.values(t)[0]);
  console.log('Tables found:', tableNames);

  let sqlDump = '-- EasySell Database Backup\n';
  sqlDump += '-- Generated by Antigravity AI\n';
  sqlDump += '-- Date: ' + new Date().toLocaleString() + '\n\n';
  sqlDump += 'SET NAMES utf8mb4;\n';
  sqlDump += 'SET FOREIGN_KEY_CHECKS = 0;\n\n';

  for (const table of tableNames) {
    console.log(`Extracting table: ${table}...`);
    
    // Get Create Table statement
    const [createTable] = await connection.query(`SHOW CREATE TABLE \`${table}\``);
    sqlDump += `\n-- Table structure for \`${table}\`\n`;
    sqlDump += `DROP TABLE IF EXISTS \`${table}\`;\n`;
    sqlDump += createTable[0]['Create Table'] + ';\n\n';

    // Get Data
    const [rows] = await connection.query(`SELECT * FROM \`${table}\``);
    if (rows.length > 0) {
      sqlDump += `-- Dumping data for \`${table}\`\n`;
      const keys = Object.keys(rows[0]);
      const columns = keys.map(k => `\`${k}\``).join(', ');
      
      for (const row of rows) {
        const values = Object.values(row).map(v => {
          if (v === null) return 'NULL';
          if (typeof v === 'boolean') return v ? 1 : 0;
          if (typeof v === 'number') return v;
          if (v instanceof Date) return `'${v.toISOString().slice(0, 19).replace('T', ' ')}'`;
          if (typeof v === 'string') {
             return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r')}'`;
          }
          return `'${v}'`;
        }).join(', ');
        
        sqlDump += `INSERT INTO \`${table}\` (${columns}) VALUES (${values});\n`;
      }
    }
  }

  sqlDump += '\nSET FOREIGN_KEY_CHECKS = 1;\n';

  const outputPath = path.join(process.cwd(), 'easysell_db_backup.sql');
  fs.writeFileSync(outputPath, sqlDump);
  console.log(`\n✅ Backup completed! Saved to: ${outputPath}`);

  await connection.end();
}

extract().catch(err => {
    console.error('❌ Backup failed:', err.message);
    process.exit(1);
});
